name: Deploy Jekyll site to GitHub Pages

on:
  # Запускается при пуше в ветку `main`
  push:
    branches: ["main"]

  # Позволяет запускать workflow вручную из вкладки Actions
  workflow_dispatch:

# Устанавливаем права для GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Ограничиваем одновременные деплои
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Устанавливаем Ruby и зависимости для Jekyll
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1  # Указываем версию Ruby
          bundler-cache: true  # Кэшируем зависимости Bundler

      # Шаг 3: Устанавливаем зависимости Jekyll
      - name: Install Jekyll and dependencies
        run: |
          gem install bundler
          bundle install

      # Шаг 4: Собираем сайт с помощью Jekyll
      - name: Build with Jekyll
        run: bundle exec jekyll build --destination ./_site

      # Шаг 5: Загружаем собранный сайт как артефакт
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site  # Указываем папку с собранным сайтом

  deploy:
    # Настройки окружения для GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build  # Зависит от шага `build`
    steps:
      # Шаг 6: Публикуем сайт на GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4